-- Enable PostGIS for spatial queries and citext for case-insensitive emails.
-- gen_random_uuid() is built into Postgres core since v13, so no uuid-ossp needed.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS citext;

-- ==========================================
-- 1. ENUMS (Custom Types)
-- ==========================================
CREATE TYPE user_role AS ENUM ('TENANT', 'OWNER', 'AGENCY', 'ADMIN');
CREATE TYPE target_tenant AS ENUM ('BOYS_ONLY', 'GIRLS_ONLY', 'STUDENT', 'FAMILY', 'ANY');
CREATE TYPE property_type AS ENUM ('STUDIO', 'S_PLUS_1', 'S_PLUS_2', 'S_PLUS_3', 'S_PLUS_4', 'COLOCATION', 'HOUSE', 'VILLA');
CREATE TYPE listing_status AS ENUM ('PENDING', 'ACTIVE', 'RENTED', 'ARCHIVED', 'SCRAPED_UNVERIFIED');
CREATE TYPE transaction_type AS ENUM ('RECHARGE', 'CONTACT_UNLOCK', 'BONUS_SIGNUP', 'REFUND');
CREATE TYPE payment_method AS ENUM ('FLOUCI', 'D17', 'KONNECT', 'OOREDOO_USSD', 'ORANGE_USSD', 'TUNISIE_TELECOM_USSD', 'ADMIN_MANUAL');

-- ==========================================
-- 2. USERS TABLE
-- ==========================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number VARCHAR(20) UNIQUE NOT NULL, -- e.g. "+21622111222"
    full_name VARCHAR(100) NOT NULL,
    email CITEXT UNIQUE, -- case-insensitive: Ali@x.com and ali@x.com collide
    password_hash TEXT NOT NULL,
    role user_role NOT NULL DEFAULT 'TENANT',
    points_balance INT NOT NULL DEFAULT 15 CHECK (points_balance >= 0), -- 15 bonus points at registration
    is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    profile_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index on phone number for fast login lookups
CREATE INDEX idx_users_phone ON users(phone_number);

-- ==========================================
-- 3. LISTINGS TABLE (With Spatial Features)
-- ==========================================
CREATE TABLE listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES users(id) ON DELETE SET NULL, -- NULL if scraped and unclaimed
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price_tnd NUMERIC(10, 2) NOT NULL CHECK (price_tnd >= 0), -- Rent in Tunisian Dinar (TND)
    deposit_tnd NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (deposit_tnd >= 0), -- Caution / Deposit

    -- Tunisian specific house specs
    property_type property_type NOT NULL DEFAULT 'S_PLUS_1',
    target_tenant target_tenant NOT NULL DEFAULT 'ANY',
    bedrooms INT NOT NULL DEFAULT 1,
    bathrooms INT NOT NULL DEFAULT 1,
    has_climatisation BOOLEAN NOT NULL DEFAULT FALSE,
    has_chauffage_central BOOLEAN NOT NULL DEFAULT FALSE,
    has_wifi BOOLEAN NOT NULL DEFAULT FALSE,
    has_elevator BOOLEAN NOT NULL DEFAULT FALSE,
    is_furnished BOOLEAN NOT NULL DEFAULT FALSE,
    surface_m2 INT,

    -- Location Data
    city VARCHAR(100) NOT NULL, -- e.g., "Tunis", "Sousse", "Ariana"
    delegation VARCHAR(100) NOT NULL, -- e.g., "La Soukra", "Les Berges du Lac"
    address_text TEXT,

    -- PostGIS Spatial Location Field (SRID 4326 = standard WGS84 GPS coords)
    location GEOGRAPHY(Point, 4326) NOT NULL,

    -- Status & Moderation
    status listing_status NOT NULL DEFAULT 'ACTIVE',
    is_verified_by_agency BOOLEAN NOT NULL DEFAULT FALSE,
    scraped_source_url TEXT, -- URL if generated by Python scraper

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Spatial GIST index for map bounding-box / radius queries.
-- IMPORTANT: query this column directly as geography (e.g. `location && ST_MakeEnvelope(...)::geography`
-- or `ST_DWithin(location, point, meters)`). Casting `location` to geometry in a query defeats this index.
CREATE INDEX idx_listings_location ON listings USING GIST(location);
CREATE INDEX idx_listings_owner ON listings(owner_id);
CREATE INDEX idx_listings_city_delegation ON listings(city, delegation);
CREATE INDEX idx_listings_price ON listings(price_tnd);
CREATE INDEX idx_listings_status ON listings(status);

-- ==========================================
-- 4. LISTING IMAGES
-- ==========================================
CREATE TABLE listing_images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_listing_images_listing_id ON listing_images(listing_id);

-- ==========================================
-- 5. POINTS & TRANSACTIONS LOG
-- ==========================================
CREATE TABLE point_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount INT NOT NULL, -- e.g., +50 for recharge, -5 for contact unlock
    type transaction_type NOT NULL,
    payment_method payment_method,
    payment_reference VARCHAR(255), -- Transaction ID from Flouci / D17 / USSD
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transactions_user ON point_transactions(user_id);

-- ==========================================
-- 6. UNLOCKED CONTACTS LOG
-- ==========================================
-- Tracks which tenant unlocked which owner's listing so they aren't charged twice.
CREATE TABLE unlocked_contacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id UUID NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    points_spent INT NOT NULL DEFAULT 5,
    unlocked_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_tenant_listing_unlock UNIQUE(tenant_id, listing_id)
);

-- ==========================================
-- 7. updated_at AUTO-TOUCH TRIGGER
-- ==========================================
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_modtime BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_listings_modtime BEFORE UPDATE ON listings FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- Log spatial engine version to Docker console for a quick sanity check on boot.
SELECT PostGIS_Full_Version();
