-- Enable PostGIS extension for spatial queries (Lat/Long map positioning)
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. ENUMS (Custom Types)
-- ==========================================
CREATE TYPE user_role AS ENUM ('TENANT', 'OWNER', 'AGENCY', 'ADMIN');
CREATE TYPE target_tenant AS ENUM ('BOYS_ONLY', 'GIRLS_ONLY', 'STUDENT', 'FAMILY', 'ANY');
CREATE TYPE property_type AS ENUM ('STUDIO', 'S_PLUS_1', 'S_PLUS_2', 'S_PLUS_3', 'S_PLUS_4', 'COLOCATION', 'HOUSE', 'VILLA');
CREATE TYPE listing_status AS ENUM ('PENDING', 'ACTIVE', 'RENTED', 'ARCHIVED', 'SCRAPED_UNVERIFIED');
CREATE TYPE transaction_type AS ENUM ('RECHARGE', 'CONTACT_UNLOCK', 'BONUS_SIGNUP', 'REFUND');
CREATE TYPE payment_method AS ENUM ('FLOUCI', 'D17', 'KONNECT', 'OOREDOO_USSD', 'ORANGE_USSD', 'TUNISIE_TELECOM_USSD', 'ADMIN_MANUAL');

-- ==========================================
-- 2. USERS TABLE
-- ==========================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    phone_number VARCHAR(20) UNIQUE NOT NULL, -- e.g. "+21622111222"
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    password_hash TEXT NOT NULL,
    role user_role DEFAULT 'TENANT',
    points_balance INT NOT NULL DEFAULT 15, -- 15 Bonus points given at registration
    is_phone_verified BOOLEAN DEFAULT FALSE,
    profile_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index on phone number for fast login lookups
CREATE INDEX idx_users_phone ON users(phone_number);

-- ==========================================
-- 3. LISTINGS TABLE (With Spatial Features)
-- ==========================================
CREATE TABLE listings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    owner_id UUID REFERENCES users(id) ON DELETE SET NULL, -- NULL if scraped and unclaimed
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price_tnd NUMERIC(10, 2) NOT NULL, -- Rent in Tunisian Dinar (TND)
    deposit_tnd NUMERIC(10, 2) DEFAULT 0, -- Caution / Deposit
    
    -- Tunisian specific house specs
    property_type property_type NOT NULL DEFAULT 'S_PLUS_1',
    target_tenant target_tenant NOT NULL DEFAULT 'ANY',
    bedrooms INT DEFAULT 1,
    bathrooms INT DEFAULT 1,
    has_climatisation BOOLEAN DEFAULT FALSE,
    has_chauffage_central BOOLEAN DEFAULT FALSE,
    has_wifi BOOLEAN DEFAULT FALSE,
    has_elevator BOOLEAN DEFAULT FALSE,
    is_furnished BOOLEAN DEFAULT FALSE,
    surface_m2 INT,

    -- Location Data
    city VARCHAR(100) NOT NULL, -- e.g., "Tunis", "Sousse", "Ariana"
    delegation VARCHAR(100) NOT NULL, -- e.g., "La Soukra", "Les Berges du Lac"
    address_text TEXT,
    
    -- PostGIS Spatial Location Field (SRID 4326 = standard WGS84 GPS coords)
    location GEOGRAPHY(Point, 4326) NOT NULL,

    -- Status & Moderation
    status listing_status DEFAULT 'ACTIVE',
    is_verified_by_agency BOOLEAN DEFAULT FALSE, -- Flag for Phase 5 managed service
    scraped_source_url TEXT DEFAULT NULL, -- URL if generated by Python scraper
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Spatial GIST Index for high-speed map bounding box and radius queries
CREATE INDEX idx_listings_location ON listings USING GIST(location);
-- Normal Index for filtering
CREATE INDEX idx_listings_city_delegation ON listings(city, delegation);
CREATE INDEX idx_listings_price ON listings(price_tnd);
CREATE INDEX idx_listings_status ON listings(status);

-- ==========================================
-- 4. LISTING IMAGES
-- ==========================================
CREATE TABLE listing_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    listing_id UUID REFERENCES listings(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_listing_images_listing_id ON listing_images(listing_id);

-- ==========================================
-- 5. POINTS & TRANSACTIONS LOG
-- ==========================================
CREATE TABLE point_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    amount INT NOT NULL, -- e.g., +50 for recharge, -5 for contact unlock
    type transaction_type NOT NULL,
    payment_method payment_method,
    payment_reference VARCHAR(255), -- Transaction ID from Flouci / D17 / USSD
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transactions_user ON point_transactions(user_id);

-- ==========================================
-- 6. UNLOCKED CONTACTS LOG
-- ==========================================
-- Tracks which tenant unlocked which landlord's listing so they don't get charged twice
CREATE TABLE unlocked_contacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID REFERENCES users(id) ON DELETE CASCADE,
    listing_id UUID REFERENCES listings(id) ON DELETE CASCADE,
    points_spent INT NOT NULL DEFAULT 5,
    unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_tenant_listing_unlock UNIQUE(tenant_id, listing_id)
);

-- ==========================================
-- 7. REVIEWS & RATINGS
-- ==========================================
CREATE TABLE reviews (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    listing_id UUID REFERENCES listings(id) ON DELETE CASCADE,
    reviewer_id UUID REFERENCES users(id) ON DELETE CASCADE,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 8. HELPER FUNCTIONS & TRIGGERS
-- ==========================================

-- Function to auto-update updated_at field
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_modtime BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
CREATE TRIGGER update_listings_modtime BEFORE UPDATE ON listings FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- Function to search listings within a spatial bounding box (for map view)
CREATE OR REPLACE FUNCTION get_listings_in_bounding_box(
    min_lat FLOAT,
    min_lng FLOAT,
    max_lat FLOAT,
    max_lng FLOAT
)
RETURNS SETOF listings AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM listings
    WHERE status = 'ACTIVE'
    AND location::geometry && ST_MakeEnvelope(min_lng, min_lat, max_lng, max_lat, 4326);
END;
$$ LANGUAGE plpgsql;

-- Log spatial engine version to Docker console
SELECT PostGIS_Full_Version();